[project]
name = "call-me-maybe"
version = "0.1.0"
description = "Function calling tool that translates natural language prompts into structured function calls using constrained decoding with a small LLM model."
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "llm-sdk",
    "numpy>=2.0.0",
    "pydantic>=2.0",
]

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "line-profiler>=5.0.2",
    "mypy>=1.20.1",
]

[tool.uv.workspace]
members = [
    "llm_sdk",
]

[tool.uv.sources]
llm-sdk = { workspace = true }
